export default {
  // 栏目
  ColumnAdd: '/admin/column/add',
  ColumnUpdata: '/admin/column/update',
  ColumnDelete: '/admin/column/delete',
  ColumnQuery: '/admin/column/query',
  ColumnFetch: '/admin/column/fetch',
  // 单页
  PageAdd: '/admin/page/add',
  PageUpdata: '/admin/page/update',
  PageDelete: '/admin/page/delete',
  PageQuery: '/admin/page/query',
  PageFetch: '/admin/page/fetch',
  // 菜单
  NavAdd: '/admin/nav/add',
  NavUpdata: '/admin/nav/update',
  NavDelete: '/admin/nav/delete',
  NavQuery: '/admin/nav/query',
  NavFetch: '/admin/nav/fetch',
  // 内容
  ContentAdd: '/admin/content/add',
  ContentUpdata: '/admin/content/update',
  ContentDelete: '/admin/content/delete',
  ContentQuery: '/admin/content/query',
  ContentFetch: '/admin/content/fetch',
  // 配置
  InfoAdd: '/admin/info/add',
  InfoUpdata: '/admin/info/update',
  InfoDelete: '/admin/info/delete',
  InfoQuery: '/admin/info/query',
  InfoFetch: '/admin/info/fetch',
  // 媒体
  FileUpload: '/admin/file/upload',
  FileDownload: '/admin/file/download',
  FileDelete: '/admin/file/delete',
  FileQuery: '/admin/file/query',
  FileFetch: '/admin/file/fetch',
};
